title: Steviemo </a-software-blog>
description: >- # this means to ignore newlines until "baseurl:"
  A place to gather my experiences and thoughts as I engineer server, web, iOS and Android software.
author: "Stephen Morrison"
email: stephen.dmorrison@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://steveimo.co" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima
plugins:
  - jekyll-feed

# Minima social links
twitter_username: steviemo83
github_username:  steviemo

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
